#!bash
# webtaku(1) completion

function __webtaku_append_space()
{
	# append space if the word doesn't end with "="
	cat | sed -re "s/[^=]$/\0 /"
}

function __webtaku_complete_wordlist()
{
	__webtaku_append_space <<WORDLIST
--format=
--output=
--accept-language=
--cookie=
--user-agent=
--min-size=
--scaled-size=
--timer=
--crop
--silent
--version
WORDLIST
}

function __webtaku_complete_wordlist_format()
{
	__webtaku_append_space <<WORDLIST
BMP
JPG
PNG
PPM
XBM
XPM
WORDLIST
}

function __webtaku_complete()
{
	# remove "=" from wordbreak list
	COMP_WORDBREAKS="${COMP_WORDBREAKS/\=/}"

	local wordlist=""
	local current=${COMP_WORDS[COMP_CWORD]}

	case $current in
		--format=*)
			# prepend "--format="
			wordlist=`__webtaku_complete_wordlist_format | sed -re "s/^/--format=/"`;;

		*)
			wordlist=`__webtaku_complete_wordlist`;;
	esac

	IFS=$'\n' COMPREPLY=(`compgen -W "${wordlist}" -- "${current}"`)
}

complete -o nospace -F __webtaku_complete webtaku
